### ISSUE TITLE
Highlight GSQL code

### ISSUE THREAD

**Issue by canbax** [canbax/davraz#11]
try using https://github.com/TigerGraph-DevLabs/highlightjs-gsql to highlight GSQL codes

**Comment by canbax** [comment]
I tried but couldn't manage it, the library might be erroneos. Opened https://github.com/TigerGraph-DevLabs/highlightjs-gsql/issues/1

**Comment by prk2331** [comment]
Hello @canbax 
Can you please let me know why this slow actually I set up Tiger Graph in my Ubuntu instance, So the Graph having 15000 records approx., So when I click on Get Neighbors in the Angular UI code behind the scene this will call the "Node edges" API in Node JS, and after sometime loading got stopped and no neighbors will came into the Picture on UI and API stopped, so when the vertex having some neighbors this will works fine, So what we can do if we have sometime more records to be fetched, why this slow in response while getting the neighbors, what approach can we take so the response time decreased.

**Comment by canbax** [comment]
@prk2331 I have no idea. There might be too many HTTP requests or too much data. It can have very different reasons
